# Generated by Django 3.2.4 on 2021-06-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='max_sentences',
            field=models.IntegerField(default=10),
        ),
    ]
