# Generated by Django 3.2.4 on 2021-07-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_max_sentences'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='end_scan_page',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='start_scan_page',
            field=models.IntegerField(null=True),
        ),
    ]
