# Generated by Django 3.2.4 on 2021-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20210813_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='stripe_subscription_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stripeid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
