# Generated by Django 3.2.4 on 2021-08-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20210813_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan'),
        ),
    ]
